
-- Criação de tabela com dados de identificação do cliente

CREATE TABLE CLIENTES
(
  CLIENT_GROUP_ID int NOT NULL,
  CLIENT_NAME_ID int NOT NULL PRIMARY KEY,
  CLIENT_GROUP varchar2(50) NOT NULL,
  CLIENT_NAME varchar2(50) NOT NULL,
  CLIENT_TAXID SMALLINT NOT NULL,
  CLIENT_SEGMENT varchar2(15) NOT NULL,
  CLIENT_HIGH nchar(1) NOT NULL
);

--Criação de sequência e inserção de dados na tabela

CREATE SEQUENCE CLIENT_NAME_ID_seq
START WITH 1000 
INCREMENT BY 1 
MAXVALUE 1050;

CREATE SEQUENCE CLIENT_GROUP_ID_seq
START WITH 10000
INCREMENT BY 10 
MAXVALUE 11000;

INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'CIA BRASILEIRA DE DIST','SUPERMERCADOS PAO DE ACUCAR S/A', '47508411000156','ALIMENTICIO','Y');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'CIA BRASILEIRA DE DIST','SUPERMERCADO EXTRA LTDA', '10864769000101','ALIMENTICIO', 'Y');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'CIA BRASILEIRA DE DIST','RAIA DROGASIL S/A', '61585865027866', 'FARMACEUTICO','Y' );
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'COMPANHIA DE BEBIDAS DAS AMERICAS - AMBEV','AMBEV S.A (STELLA ARTOIS)', '07526557000100','BEBIDAS','N');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'COMPANHIA DE BEBIDAS DAS AMERICAS - AMBEV','CIA CERVEJARIA BRAHMA', '33366980000108','BEBIDAS','Y');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'GRUPO DE MODA SOMA SA','CIA HERING', '78876950000171','VESTUARIO','Y');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'GRUPO DE MODA SOMA SA','ANIMALE LTDA', '10285590006807','VESTUARIO','N');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'GRUPO TRENDFOOD','CIB COMERCIO DE ALIMENTOS LTDA (CHINA IN BOX)', '10537731000124','FAST FOOD, RESTAURANTE E DELIVERY','Y');
INSERT INTO CLIENTES VALUES (CLIENT_GROUP_ID_seq.NEXTVAL,CLIENT_NAME_ID_seq.NEXTVAL, 'GRUPO TRENDFOOD','GROUP RR CULINARIA JAPONESA EIRELI (GENDAI)', '12850595000153','FAST FOOD, RESTAURANTE E DELIVERY','Y');

SELECT * FROM CLIENTES; 
    


    
    
    

